/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfParam {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::ConfParamType,
    #[serde(rename = "description")]
    pub description: Box<models::ConfParamDescription>,
    #[serde(rename = "value")]
    pub value: Box<models::ConfParamValue>,
}

impl ConfParam {
    pub fn new(id: String, r#type: models::ConfParamType, description: models::ConfParamDescription, value: models::ConfParamValue) -> ConfParam {
        ConfParam {
            id,
            name: None,
            r#type,
            description: Box::new(description),
            value: Box::new(value),
        }
    }
}

