/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfParamType {
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "byte")]
    Byte,
    #[serde(rename = "binary")]
    Binary,
    #[serde(rename = "range")]
    Range,
    #[serde(rename = "integer_range")]
    IntegerRange,
    #[serde(rename = "date_range")]
    DateRange,
    #[serde(rename = "datetime_range")]
    DatetimeRange,
    #[serde(rename = "numeric_value_list")]
    NumericValueList,
    #[serde(rename = "integer_value_list")]
    IntegerValueList,
    #[serde(rename = "string_value_list")]
    StringValueList,
    #[serde(rename = "date_value_list")]
    DateValueList,
    #[serde(rename = "datetime_value_list")]
    DatetimeValueList,
    #[serde(rename = "byte_value_list")]
    ByteValueList,
    #[serde(rename = "binary_value_list")]
    BinaryValueList,

}

impl std::fmt::Display for ConfParamType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boolean => write!(f, "boolean"),
            Self::Byte => write!(f, "byte"),
            Self::Binary => write!(f, "binary"),
            Self::Range => write!(f, "range"),
            Self::IntegerRange => write!(f, "integer_range"),
            Self::DateRange => write!(f, "date_range"),
            Self::DatetimeRange => write!(f, "datetime_range"),
            Self::NumericValueList => write!(f, "numeric_value_list"),
            Self::IntegerValueList => write!(f, "integer_value_list"),
            Self::StringValueList => write!(f, "string_value_list"),
            Self::DateValueList => write!(f, "date_value_list"),
            Self::DatetimeValueList => write!(f, "datetime_value_list"),
            Self::ByteValueList => write!(f, "byte_value_list"),
            Self::BinaryValueList => write!(f, "binary_value_list"),
        }
    }
}

impl Default for ConfParamType {
    fn default() -> ConfParamType {
        Self::Boolean
    }
}

