/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfParamChange {
    #[serde(rename = "value")]
    pub value: Box<models::SloDescriptionTarget>,
}

impl ConfParamChange {
    pub fn new(value: models::SloDescriptionTarget) -> ConfParamChange {
        ConfParamChange {
            value: Box::new(value),
        }
    }
}

