/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfParamDescription {
    #[serde(rename = "minValue", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<Box<models::SloDescriptionMinValue>>,
    #[serde(rename = "maxValue", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<Box<models::SloDescriptionMaxValue>>,
    #[serde(rename = "valueList", skip_serializing_if = "Option::is_none")]
    pub value_list: Option<Vec<models::ConfParamDescriptionValueListInner>>,
}

impl ConfParamDescription {
    pub fn new() -> ConfParamDescription {
        ConfParamDescription {
            min_value: None,
            max_value: None,
            value_list: None,
        }
    }
}

