/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Slo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type")]
    pub r#type: models::SloType,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Box<models::SloValue>>,
    #[serde(rename = "description")]
    pub description: Box<models::SloDescription>,
}

impl Slo {
    pub fn new(id: String, r#type: models::SloType, description: models::SloDescription) -> Slo {
        Slo {
            id,
            name: None,
            r#type,
            value: None,
            description: Box::new(description),
        }
    }
}

