/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SloType {
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "range")]
    Range,
    #[serde(rename = "integer_range")]
    IntegerRange,
    #[serde(rename = "date_range")]
    DateRange,
    #[serde(rename = "datetime_range")]
    DatetimeRange,
    #[serde(rename = "target_value")]
    TargetValue,
    #[serde(rename = "integer_target_value")]
    IntegerTargetValue,
    #[serde(rename = "string_target_value")]
    StringTargetValue,
    #[serde(rename = "date_target_value")]
    DateTargetValue,
    #[serde(rename = "datetime_target_value")]
    DatetimeTargetValue,

}

impl std::fmt::Display for SloType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Boolean => write!(f, "boolean"),
            Self::Range => write!(f, "range"),
            Self::IntegerRange => write!(f, "integer_range"),
            Self::DateRange => write!(f, "date_range"),
            Self::DatetimeRange => write!(f, "datetime_range"),
            Self::TargetValue => write!(f, "target_value"),
            Self::IntegerTargetValue => write!(f, "integer_target_value"),
            Self::StringTargetValue => write!(f, "string_target_value"),
            Self::DateTargetValue => write!(f, "date_target_value"),
            Self::DatetimeTargetValue => write!(f, "datetime_target_value"),
        }
    }
}

impl Default for SloType {
    fn default() -> SloType {
        Self::Boolean
    }
}

