/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SloDescriptionMaxRange {
    Number(f64),
    String(String),
}

impl Default for SloDescriptionMaxRange {
    fn default() -> Self {
        Self::Number(Default::default())
    }
}

