/*
 * Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: research-0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SloDescription {
    #[serde(rename = "minValue", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<Box<models::SloDescriptionMinValue>>,
    #[serde(rename = "maxValue", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<Box<models::SloDescriptionMaxValue>>,
    #[serde(rename = "minRange", skip_serializing_if = "Option::is_none")]
    pub min_range: Option<Box<models::SloDescriptionMinValue>>,
    #[serde(rename = "maxRange", skip_serializing_if = "Option::is_none")]
    pub max_range: Option<Box<models::SloDescriptionMaxRange>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<models::SloDescriptionTarget>>,
}

impl SloDescription {
    pub fn new() -> SloDescription {
        SloDescription {
            min_value: None,
            max_value: None,
            min_range: None,
            max_range: None,
            target: None,
        }
    }
}

